### ISSUE TITLE
flex.promise/resource that accepts fetcher function with multi args

### ISSUE THREAD

**Issue by rafaeldelboni** [lilactown/flex#12]
Would you be interested in a PR with a new (breaking) version of flex.promise/resource that accepts a fetcher function that could be called with multiple arguments?

I'm using one in a personal project and I'm liking it so far.

You can check it [here](https://github.com/clj-codes/docs.frontend/blob/main/src/codes/clj/docs/frontend/infra/flex/promise.cljs), I even [rewrote your tests](https://github.com/clj-codes/docs.frontend/blob/main/test/codes/clj/docs/frontend/infra/flex/promise_test.cljs) to validate the idea and is a simple way to show you how it works _(ignore the promesa stuff, they are enabling async tests work in jsdom environment)_

**The breaking change is that it doesn't call itself in the initialization**

**Comment by lilactown** [comment]
I guess two questions:
1. Why do you want a fetcher function with multiple args? Could you pass a map or a vector instead?
2. How does not calling the fetcher on instantiation change the ergonomics? I would imagine that it's easier to use with React, since you can wait until after mount to run the mutation.

I think that not calling the resource (i.e. not fetching) on instantiation might make sense regardless of of multiple args.

**Comment by rafaeldelboni** [comment]
1. Yes I would be fine with an array of args 
2. Exactly, in this project I'm using reitit and in initializing some fetch on the [controller start ](https://github.com/clj-codes/docs.frontend/blob/main/src/codes/clj/docs/frontend/routes.cljs)(when start navigating in the route after argument validation) and then I can use a hook to wait for the query being done in the react side.

**Comment by lilactown** [comment]
yeah that makes sense. FWIW I don't see a reason not to also allow multiple args, just asking the question. I'd accept a PR with the change you made!
